spring.application.name=marketplace
server.port=${PORT:8080}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

server.address=0.0.0.0

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always